{
  "messages": [
    {
      "error_id": "",
      "references": [
        {
          "column": 9,
          "file": "/home/yo30qaqy/data-race-detection-benchmark-suite/results-20250730-140308/SPMDIR-MUST/sync/005-MPI-sync-lock-flush-local-yes.c",
          "line": 42
        },
        {
          "column": 33,
          "file": "/home/yo30qaqy/data-race-detection-benchmark-suite/results-20250730-140308/SPMDIR-MUST/sync/005-MPI-sync-lock-flush-local-yes.c",
          "line": 44
        }
      ],
      "text": "Found get operation/call at results-20250730-140308/SPMDIR-MUST/sync/005-MPI-sync-lock-flush-local-yes.c:42:9 which is in conflict with load operation/call at results-20250730-140308/SPMDIR-MUST/sync/005-MPI-sync-lock-flush-local-yes.c:44:33 before release",
      "type": "Local Data Race"
    }
  ]
}
