{
  "messages": [
    {
      "error_id": "",
      "references": [
        {
          "column": 9,
          "file": "/home/yo30qaqy/data-race-detection-benchmark-suite/results-20250730-140308/SPMDIR-MUST/conflict/006-MPI-conflict-get-put-local-yes.c",
          "line": 39
        },
        {
          "column": 9,
          "file": "/home/yo30qaqy/data-race-detection-benchmark-suite/results-20250730-140308/SPMDIR-MUST/conflict/006-MPI-conflict-get-put-local-yes.c",
          "line": 41
        }
      ],
      "text": "Found get operation/call at results-20250730-140308/SPMDIR-MUST/conflict/006-MPI-conflict-get-put-local-yes.c:39:9 which is in conflict with put operation/call at results-20250730-140308/SPMDIR-MUST/conflict/006-MPI-conflict-get-put-local-yes.c:41:9 before release",
      "type": "Local Data Race"
    }
  ]
}
